# Generated by Django 5.2.1 on 2025-05-13 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forage',
            fields=[
                ('idForage', models.AutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('dateDebut', models.DateField(blank=True, null=True)),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('dureePrevistionnelle', models.IntegerField(blank=True, null=True)),
                ('dureeActuelle', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseStandard',
            fields=[
                ('idPhaseStandard', models.AutoField(primary_key=True, serialize=False)),
                ('nomDePhase', models.CharField(default='0')),
                ('coutPrevistionel', models.FloatField()),
                ('delaiPrevistionel', models.IntegerField()),
                ('depthStandard', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rapport_imported',
            fields=[
                ('id_rapport_imported', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.FileField(upload_to='')),
                ('date_upload', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=500)),
                ('priority_remarque', models.CharField(choices=[('HAUTE', 'Haute'), ('MOYENNE', 'Moyenne'), ('FAIBLE', 'Faible')], default='MOYENNE', max_length=20)),
                ('observation_remarque', models.CharField(max_length=500)),
                ('solution_remarque', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('ingenieur_terrain', 'Ingénieur Terrain'), ('responsable', 'Responsable'), ('admin', 'Administrateur')], default='ingenieur_terrain', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('idRapport', models.AutoField(primary_key=True, serialize=False)),
                ('numRapport', models.IntegerField(default=0)),
                ('dateActuelle', models.DateField()),
                ('depthActuel', models.FloatField()),
                ('idForage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.forage')),
                ('id_rapport_imported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rapport_imported')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('idPhase', models.AutoField(primary_key=True, serialize=False)),
                ('delaiActuel', models.IntegerField()),
                ('coutActuel', models.FloatField()),
                ('coutCumulatifActuel', models.FloatField()),
                ('currentOperation', models.CharField(default='operation X')),
                ('plannedOperation', models.CharField(default='operation Y')),
                ('idForage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.forage')),
                ('idPhaseStandard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.phasestandard')),
                ('idRapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rapport')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('idnotif', models.AutoField(primary_key=True, serialize=False)),
                ('dateNotif', models.DateField()),
                ('analysed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idRapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rapport')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
