# Generated by Django 5.2.3 on 2025-06-12 19:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forage',
            fields=[
                ('id_forage', models.AutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('duree_previstionnelle', models.IntegerField(blank=True, default=70, null=True)),
                ('cout_previstionnel', models.FloatField(blank=True, default=11056000.0, null=True)),
                ('cout_actuel', models.FloatField(blank=True, default=0, null=True)),
                ('duration_actuelle', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'forage',
            },
        ),
        migrations.CreateModel(
            name='PhaseStandard',
            fields=[
                ('id_phase_standard', models.AutoField(primary_key=True, serialize=False)),
                ('nom_de_phase', models.CharField(default='0', max_length=100)),
                ('cout_previstionel', models.FloatField()),
                ('delai_previstionel', models.IntegerField()),
                ('depth_standard', models.FloatField()),
            ],
            options={
                'db_table': 'phase_standard',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('ingenieur_terrain', 'Ingénieur Terrain'), ('responsable', 'Responsable'), ('admin', 'Administrateur')], default='ingenieur_terrain', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id_phase', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField(default='2024-01-01')),
                ('depth_actuel', models.FloatField(default=0)),
                ('delai_actuel', models.IntegerField()),
                ('cout_actuel', models.FloatField()),
                ('cout_cumulatif_actuel', models.FloatField()),
                ('current_operation', models.CharField(default='operation X', max_length=200)),
                ('planned_operation', models.CharField(default='operation Y', max_length=200)),
                ('etat', models.CharField(choices=[('on_time', 'On Time'), ('slightly_ahead', 'Slightly Ahead'), ('delayed', 'Delayed'), ('in_progress', 'In Progress')], default='in_progress', max_length=20)),
                ('id_forage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.forage')),
                ('id_phase_standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.phasestandard')),
            ],
            options={
                'db_table': 'phase',
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id_rapport', models.AutoField(primary_key=True, serialize=False)),
                ('num_rapport', models.IntegerField(default=0)),
                ('date_actuelle', models.DateField(default='2024-01-01')),
                ('nom_phase', models.CharField(default='phase X', max_length=100)),
                ('id_forage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.forage')),
            ],
            options={
                'db_table': 'rapport',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notif', models.AutoField(primary_key=True, serialize=False)),
                ('date_notif', models.DateField(default=django.utils.timezone.now)),
                ('analysed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('id_rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rapport')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RapportImported',
            fields=[
                ('id_rapport_imported', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.FileField(upload_to='rapports/')),
                ('date_upload', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=500)),
                ('priority_remarque', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('observation_remarque', models.CharField(max_length=500)),
                ('solution_remarque', models.CharField(max_length=800)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rapport_imported',
            },
        ),
        migrations.AddField(
            model_name='rapport',
            name='id_rapport_imported',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.rapportimported'),
        ),
    ]
