# Generated by Django 5.2.3 on 2025-06-12 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='id_rapport',
            new_name='rapport',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='id_user',
            new_name='user',
        ),
    ]
