# Generated by Django 5.2.3 on 2025-06-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forage',
            name='coutActuel',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='forage',
            name='coutprevistionnel',
            field=models.FloatField(blank=True, default=11056000.0, null=True),
        ),
        migrations.AddField(
            model_name='forage',
            name='durationActuelle',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forage',
            name='dureePrevistionnelle',
            field=models.IntegerField(blank=True, default=70, null=True),
        ),
    ]
