# Generated by Django 5.2.1 on 2025-05-14 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rapport_imported_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapport_imported',
            old_name='id_user',
            new_name='user',
        ),
    ]
