# Generated by Django 5.2.3 on 2025-06-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_forage_coutactuel_forage_coutprevistionnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='etat',
            field=models.CharField(choices=[('on time', 'On Time'), ('slightly ahead', 'Slightly Ahead'), ('delayed', 'Delayed'), ('inprogress', 'In Progress')], default='on time', max_length=20),
        ),
    ]
