# Generated by Django 5.2.1 on 2025-05-14 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_id_user_rapport_imported_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='idForage',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.forage'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='numRapport',
            field=models.IntegerField(default=2),
        ),
    ]
