# Generated by Django 5.2.3 on 2025-06-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_phase_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='etat',
            field=models.CharField(choices=[('on time', 'On Time'), ('slightly ahead', 'Slightly Ahead'), ('delayed', 'Delayed'), ('inprogress', 'In Progress')], default='in progress', max_length=20),
        ),
    ]
