# Generated by Django 5.2.3 on 2025-06-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_phase_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport_imported',
            name='priority_remarque',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20),
        ),
    ]
