# Generated by Django 5.2.1 on 2025-05-14 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_rapport_idforage_alter_rapport_numrapport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='idForage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.forage'),
        ),
    ]
