# Generated by Django 5.2.3 on 2025-06-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_rapport_imported_priority_remarque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='etat',
            field=models.CharField(choices=[('on time', 'On Time'), ('slightly ahead', 'Slightly Ahead'), ('delayed', 'Delayed'), ('inprogress', 'In Progress')], default='inprogress', max_length=20),
        ),
    ]
