# Generated by Django 5.2.1 on 2025-05-15 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_notification_datenotif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forage',
            name='dureeActuelle',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='idRapport',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='depthActuel',
        ),
        migrations.AddField(
            model_name='phase',
            name='dateDebut',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='phase',
            name='depthActuel',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rapport',
            name='nom_phase',
            field=models.CharField(default='phase X'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='dateActuelle',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='idForage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.forage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rapport',
            name='id_rapport_imported',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.rapport_imported'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='numRapport',
            field=models.IntegerField(default=0),
        ),
    ]
