# Generated by Django 5.2.1 on 2025-05-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_forage_dureeactuelle_remove_phase_idrapport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport_imported',
            name='url',
            field=models.FileField(upload_to='C:\\Users\\Dell\\Downloads'),
        ),
    ]
