# Generated by Django 5.2.1 on 2025-05-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_rapport_imported_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport_imported',
            name='url',
            field=models.FileField(upload_to=''),
        ),
    ]
